
    module.exports = function (app) {
        const modelName = 'invoice';
        const mongooseClient = app.get('mongooseClient');
        const { Schema } = mongooseClient;
        const schema = new Schema(
          {
            noff: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
invoicetype: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 150, index: true, trim: true },
invoicedateandtime: { type: Date, required: true },
originaleinvoicereferencenumber: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
suppliername: { type: String, required: true, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
suppliertin: { type: String, required: true, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
suppliersstregistrationnumber: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
identifiertype: { type: Schema.Types.ObjectId, ref: "identify_type" },
identifiernumber: { type: String, required: true, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
suppliermsiccode: { type: Number, required: false, min: 0, max: 10000000 },
suppliertourismtaxregistrationnumber: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
supplierbusinessactivitydescription: { type: String, required: true, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
supplieremail: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
thefirstsuppliercontactnumber: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 150, index: true, trim: true },
suppliercontactnumber: { type: Number, required: false, min: 0, max: 10000000 },
suppliercountryname: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 150, index: true, trim: true },
supplierstatename: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 150, index: true, trim: true },
suppliercityname: { type: String, required: true, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
supplierpostalzone: { type: Number, required: false, min: 0, max: 1000000 },
supplieradressline0: { type: String, required: true, unique: false, lowercase: false, uppercase: false, minLength: null, maxLength: null, index: false, trim: false },
supplieradressline1: { type: String, required: false, unique: false, lowercase: false, uppercase: false, maxLength: null, index: false, trim: false },
supplieraddressline2: { type: String, required: false, unique: false, lowercase: false, uppercase: false, maxLength: null, index: false, trim: false },
buyername: { type: String, required: true, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
buyertin: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
buyersstregistrationnumber: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
buyeridentifiertype: { type: Schema.Types.ObjectId, ref: "identify_type" },
buyerbusinessregistrationnumber: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
buyeremail: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
buyercountryname: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 150, index: true, trim: true },
buyerstatename: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 150, index: true, trim: true },
buyercityname: { type: String, required: true, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
buyerpostalzone: { type: Number, required: false, min: 0, max: 1000000 },
buyeraddressline0: { type: String, required: true, unique: false, lowercase: false, uppercase: false, maxLength: null, index: false, trim: false },
buyeraddressline1: { type: String, required: false, unique: false, lowercase: false, uppercase: false, maxLength: null, index: false, trim: false },
buyeraddressline2: { type: String, required: false, unique: false, lowercase: false, uppercase: false, maxLength: null, index: false, trim: false },
thefirstbuyercontactnumber: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 150, index: true, trim: true },
buyercontactnumber: { type: Number, required: true, min: 0, max: 1000000 },
invoicecurrency: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 150, index: true, trim: true },
currencyexchangerate: { type: Number, required: false, min: 0, max: 1000000 },
frequencyofbilling: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 150, index: true, trim: true },
billingperiodstartdate: { type: Date, required: false },
billingperiodenddate: { type: Date, required: false },
paymentmode: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 150, index: true, trim: true },
supplierbankaccountnumber: { type: Number, required: false, min: 0, max: 1000000 },
paymentterms: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
prepaymentamount: { type: Number, required: false, min: 0, max: 1000000 },
prepaymentdate: { type: Date, required: false },
prepaymentreferencenumber: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
shippingrecipientname: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
shippingrecipientcountryname: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
shippingrecipientstatename: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
shippingrecipientcityname: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
shippingrecipientpostalzone: { type: Number, required: false, min: 0, max: 1000000 },
shippingrecipientaddressline0: { type: String, required: false, unique: false, lowercase: false, uppercase: false, maxLength: null, index: false, trim: false },
shippingrecipientaddressline1: { type: String, required: false, unique: false, lowercase: false, uppercase: false, maxLength: null, index: false, trim: false },
shippingrecipientaddressline2: { type: String, required: true, unique: false, lowercase: false, uppercase: false, maxLength: null, index: false, trim: false },
shippingrecipienttin: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
shippingrecipientidentifiertype: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 150, index: true, trim: true },
shippingrecipientbusinessregistrationnumber: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
billreferencenumber: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
referencenumberofcustomsformno1: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
incoterms: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
freetradeagreementinformation: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
authorisationnumberforcertifiedexporter: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
referencenumberofcustomsformno2: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
invoicelinenumber: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 150, index: true, trim: true },
invoicelineclassification: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 150, index: true, trim: true },
productname: { type: String, required: true, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
quantity: { type: Number, required: false, min: 0, max: 1000000 },
unitprice: { type: Number, required: true, min: 0, max: 1000000 },
measurement: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 150, index: true, trim: true },
subtotal: { type: Number, required: false, min: 0, max: 1000000 },
countryoforigin: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 150, index: true, trim: true },
pretotalexcludingtax: { type: Number, required: true, min: 0, max: 1000000 },
taxtype: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 150, index: true, trim: true },
taxrate: { type: Number, required: false, min: 0, max: 1000000 },
taxamount: { type: Number, required: false, min: 0, max: 1000000 },
taxdescription: { type: String, required: false, unique: false, lowercase: false, uppercase: false, maxLength: null, index: false, trim: false },
taxexemptiondetails: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
taxexemptionamount: { type: Date, required: false },
discountrate: { type: Number, required: false, min: 0, max: 1000000 },
discountamount: { type: Number, required: false, min: 0, max: 1000000 },
discountdescription: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
feeorchargerate: { type: Number, required: false, min: 0, max: 1000000 },
feeorchargeamount: { type: Number, required: false, min: 0, max: 1000000 },
feeorchargedescription: { type: String, required: false, unique: false, lowercase: false, uppercase: false, maxLength: null, index: false, trim: false },
detailtaxtype: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 150, index: true, trim: true },
detailtotaltaxamountpertaxtype: { type: Number, required: false, min: 0, max: 1000000 },
detailtotaltaxableamount: { type: Number, required: true, min: 0, max: 1000000 },
detailsoftaxexemption: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },
amountexemptedfromtax: { type: Number, required: false, min: 0, max: 1000000 },
additionaldiscountamount: { type: Number, required: false, min: 0, max: 1000000 },
additionaldiscountdescription: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 150, index: true, trim: true },
additionalfeeamount: { type: Number, required: false, min: 0, max: 1000000 },
additionalfeedescription: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 150, index: true, trim: true },
otherfeeorchargeamounts: { type: Number, required: false, min: 0, max: 1000000 },
othrefeeorchargedescription: { type: String, required: false, unique: false, lowercase: false, uppercase: false, minLength: null, maxLength: null, index: false, trim: false },
totaldiscountvalue: { type: Number, required: false, min: 0, max: 1000000 },
totalfeeorchargeamount: { type: Number, required: false, min: 0, max: 1000000 },
totaltaxamount: { type: Number, required: true, min: 0, max: 1000000 },
totalexcludingtax: { type: Number, required: true, min: 0, max: 1000000 },
totalnetamount: { type: Number, required: false, min: 0, max: 1000000 },
totalincludingtax: { type: Number, required: false, min: 0, max: 1000000 },
roundingamount: { type: Number, required: false, min: 0, max: 1000000 },
totalpayableamount: { type: Number, required: true, min: 0, max: 1000000 },
invoicenumber: { type: String, required: true, unique: false, lowercase: false, uppercase: false, minLength: 2, maxLength: 1000, index: true, trim: true },

            
            createdBy: { type: Schema.Types.ObjectId, ref: "users", required: true },
            updatedBy: { type: Schema.Types.ObjectId, ref: "users", required: true }
          },
          {
            timestamps: true
        });
      
       
        if (mongooseClient.modelNames().includes(modelName)) {
          mongooseClient.deleteModel(modelName);
        }
        return mongooseClient.model(modelName, schema);
        
      };